"""Utility helpers for configuration, logging, randomness, and I/O."""

from __future__ import annotations

import json
import logging
import os
import pathlib
import time
from typing import Any, Dict, Tuple

import numpy as np
import yaml


def setup_logger(name: str, log_file: str | None = None, level: int = logging.INFO) -> logging.Logger:
    """Configure and return a logger with console and optional file handlers."""
    logger = logging.getLogger(name)
    logger.setLevel(level)
    if logger.handlers:
        return logger
    formatter = logging.Formatter(
        fmt="%(asctime)s | %(name)s | %(levelname)s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
    stream_handler = logging.StreamHandler()
    stream_handler.setFormatter(formatter)
    logger.addHandler(stream_handler)
    if log_file:
        os.makedirs(os.path.dirname(log_file), exist_ok=True)
        file_handler = logging.FileHandler(log_file)
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
    logger.propagate = False
    return logger


def load_config(path: str) -> Dict[str, Any]:
    """Load YAML configuration."""
    with open(path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {}
    return cfg


def apply_overrides(cfg: Dict[str, Any], overrides: Dict[str, Any]) -> Dict[str, Any]:
    """Apply CLI overrides to configuration."""
    merged = json.loads(json.dumps(cfg))  # deep copy via JSON for primitives
    for key, value in overrides.items():
        if value is None:
            continue
        merged[key] = value
    return merged


def create_rng(seed: int | None, rank: int = 0) -> np.random.Generator:
    """
    Create reproducible RNG offset by rank to ensure distinct streams in MPI runs.
    """
    base_seed = seed if seed is not None else int(time.time())
    # Avoid overflow while keeping reproducibility.
    offset_seed = (base_seed + rank * 9973) % (2**32 - 1)
    return np.random.default_rng(offset_seed)


def ensure_dir(path: str | os.PathLike[str]) -> None:
    """Create directory if missing."""
    pathlib.Path(path).mkdir(parents=True, exist_ok=True)


def read_xyz(path: str) -> np.ndarray:
    """
    Read simple XYZ format (ignores element labels) and return positions.
    """
    with open(path, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f.readlines() if line.strip()]
    try:
        n_atoms = int(lines[0])
    except (ValueError, IndexError) as exc:
        raise ValueError("XYZ file missing atom count header") from exc
    coord_lines = lines[2 : 2 + n_atoms]
    positions = []
    for line in coord_lines:
        parts = line.split()
        if len(parts) < 4:
            raise ValueError(f"XYZ line missing fields: {line}")
        positions.append([float(parts[1]), float(parts[2]), float(parts[3])])
    if len(positions) != n_atoms:
        raise ValueError("XYZ file atom count does not match provided coordinates")
    return np.asarray(positions, dtype=float)


def write_xyz(path: str, positions: np.ndarray) -> None:
    """Write coordinates to XYZ format with dummy atom label 'X'."""
    ensure_dir(os.path.dirname(path))
    n_atoms = positions.shape[0]
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"{n_atoms}\n")
        f.write("Generated by HPC Monte Carlo Molecular Optimization\n")
        for pos in positions:
            f.write(f"X {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n")


def detect_mpi() -> Tuple[Any, int, int]:
    """
    Detect MPI availability and return (comm, rank, size).

    Falls back to a mock communicator in serial mode.
    """
    try:
        from mpi4py import MPI
    except Exception:  # pragma: no cover - MPI might be absent in CI
        class _DummyComm:
            def Get_rank(self) -> int:
                return 0

            def Get_size(self) -> int:
                return 1

            def allreduce(self, value: Any, op: Any | None = None) -> Any:
                return value

            def gather(self, value: Any, root: int = 0) -> list[Any]:
                return [value]

            def bcast(self, value: Any, root: int = 0) -> Any:
                return value

        return _DummyComm(), 0, 1
    comm = MPI.COMM_WORLD
    return comm, comm.Get_rank(), comm.Get_size()
